### ISSUE TITLE
[bugreport]: KelpCommand#onCommandRegister gets executed multiply times on the same instance

### ISSUE THREAD

**Issue by DSeeLPYT** [PXAV/kelp#38] opened 2021-01-16 15:18 UTC
### Describe the bug
The onCommandRegister method on a SubCommand gets executed everytime the sub command is called.
I didn't forget the @Singleton annotation. The instance is the same.

### What do we have to do to reproduce this bug? 
1. Create a Command and a SubCommand
2. In both Commands you put in the onCommandRegister method a unique output
3. In the parent command you see the output on Kelp startup. In the sub command you see the output everytime it is executed.

### What would you expect to happen?
The onCommandRegister method in the sub command should only be called once in the application lifecycle.

### Environment information
* Operating system: Linux Kubuntu 20.10
* Java-Version: 1.8
* Kelp-Core-Version: v.0.0.5
* Version-Implementation: 1.8

**Comment by PXAV** [comment] 2021-01-17 15:38
Thank you for your bug report! I'll look into it and the bug will be fixed with the next release.

**Comment by PXAV** [comment] 2021-01-27 15:48
Hello once again, I was just trying to fix the bug, but couldn't reproduce it. My code is as follows:

Main command:
```java
@Singleton
@CreateCommand(name = "testcmd")
public class cmdtest1 extends KelpCommand {

  @Override
  public void onCommandRegister() {
    System.out.println("on command register called in main command");
  }

  @Override
  public void onCommand(KelpPlayer player, String[] args) {
    player.sendMessage("Hello!");
  }

}
```

Subcommand:
```java
@Singleton
@CreateSubCommand(name = "soos", parentCommand = cmdtest1.class)
public class cmdtest2 extends KelpCommand {

  @Override
  public void onCommandRegister() {
    System.out.println("on command register called in sub command");
  }

  @Override
  public void onCommand(KelpPlayer player, String[] args) {
    player.sendMessage("Hello! From the sub command!");
  }

}

```

On server startup, I get the `onCommandRegister` methods just as I should:
```bash
[16:41:29 INFO]: on command register called in sub command
[16:41:29 INFO]: on command register called in main command
```

But when I execute the commands (no matter if sub or main command), those messages are not printed to the console. 
So this does not seem like a bug caused by Kelp for me. Did you do any `super` calls maybe?

**Closed** 2021-01-29 09:17 UTC
Labels: bug
